language: python
python:
  - 2.7

env:
  global:
  - REPO=mcwarman/pubsub-emulator
  - CONTAINER=pubsub-emulator
  - secure: gzZUlB9dOqVnzu6KIFMPr4e0PswHu68O6GqRg2ef/CD4Jpz2JNI48+Vetb6l3PZ0rhTO7i1kIMSFDILU/XHvijwpkAixJV6izJmxY0Lr4QDkPGJvBz/EoUocDJq5Ckj0uinNDCx2GQ/Ic7XPzqKrJG/Q4umFXbPc/yDDHz/WXsNj66aWHGtJNqH3LpI8KB5dGfYrsRyF0xC5MSiPdTNvzYu22ZG2gfuzxFxeXWxslXSI6HDg+0alHgytvlcPt70EbHvfxFb29W1B5yMUpJlmDc7T/Jdx3bBx+uRX/WCnJoXNiGrBSseVHKOSl7+U5dkby1PhYfrl7csUfQ3ZavMA3okYomXfVydjqfXOG6YlCIPo8wKOP2A5R9FiIBvM052tH3G+6SiB0zRf2e0md/O5XHtfiHqUpNpHkXyVN4D15tttuCj+GFbnfVH7mmhbzGEEd8mT3xlgwoxd5R7GnDVjEPb6LWzKQRfgFUcoLvuXuJY6ILwBupmrqZBmwRu4jN0iz39v/J923X2n9rFP4Q+oQ5kYBbkRmdLiDtAj7C9nUMGmXUz4ztD7OgayMWmd7eiiSrt2WNbFqWPxdqS42hnEp6pDKfgPUazD8dg0xlWBkRvEwdbmk3hbQtq+3lMosjDlIT8AP6pUyJ6j2/rhLNYSPUOeLpysQ/LFCUzl+igjzzw=
  - secure: P9mOBoIV/GoaxO+bN+DPVPPJ0qPskuSwBF/t7QKug4RK4hQf8ujZZje7gHrG5GFTxtfcwiqBxWZoileOIIwH/CijTivELJE/Su17RNhwO1VcPdRp/xlJp+jxa7Mi4jvdtx6J2YQIpm7THgfn15H46L+bzWeri8q82RrMl0w5mfv/f99EhRwBp6VXVmRTKkSvI0OFT8vWhst7UMKzcyEBVl96lvNVbvoyV9qY+iUJVmk+NZDKVF/KF3mTGIdUDv4KGzRhGkOB/qZe4iGXm27IeCU+lEIaNJP8TeQUzK69G7GzYighbIYqEPIRNFbORfD1R/oHPFXL6v/ppYpotWFUNMavwXauw2FSYbFeVrBWQwlIJxQIsCz3/GAzEWtT50ugxt8XCYQMUjVzszgoBpNCa5M3WyRAH8RKFjS7YjJ+DkhXMbTMn9DLNa840aOF801Aq1BxtZcbJ2shToyl4N0w4yKmveQrABGBeQoPKyskkbtfphIyADaLGlP7AASo9oWkp0ijmAYmBWEQqI1hg4kb3589AtYbW8nFC9saLi8xo4qHhb0UjJSq0L9SFiyJ8rwUMrQHCDpHfbtZdjBX5D3Wrc38DAsMO7t608s0EK/gwfLYf4C2KhYMFV5DJQCXocSn1R5m7/55WbBAB1nDr7KInP0VZZ21gzuXVrn05ezqAiU=
  - secure: J2fjCCIzTEu0d71pZy8QDX/yleqjreRW82LtK/HAY/vv7ObkTiLJn9q8TyCsdIfZfNhaf/Tj8BtToG8t5qYqxPJEfZM5CtxJybAnTEnJDvC7Jc3mL1aB2P0Ny9KK+AT1iCaDIZPBnT1gGjm73JhZHqwfW9ieCrnh5ON7LNnGbb/cbadeW2hSxXXS0IWXE8rbvZtKmJI2dV/VtYrbbYYgkJlekeKtZk+Gt7glCP70aa3pxHyAjXznjonfhZH5r2xcxD48PwxK2kXB0p6GKhcL7wSOXSO4s8+Llx70mVRsAa9hI/KagWPeN+BctY/YA/5IECCElNVNvvHf6QcWdM76HuJzJsafB7d8F5TNTQTpGVdTWO5seIGPs6q++GdDeN7DVKyhx1W+qC+bE9TCX70/gTMf2L5GpuRHpPubG2sTjf6lh8TX0ccDNTia4FKIkgvxJCMAO1dOMk2qvT+lOrOsMUM3ByLb41Kpu6IY7UeWNVzySS1fpJZLWkfpDKQWYQrqxiNaXsg1SzigJ99KXj+nwWG6qAktf0hV27YY7OW4K1jac+ngNcr992MmmQ2CCccUE1EvGJrEfgRL8tvPau7p1lWomWMpMn9XqFfcoqBBDBq1BKNw32LSWZ5u0ORbfaEZZdAgg4DjmN+J5XsbDRZ9xZ+yKOFh+rPprHBTMb6WKQ0=

services:
  - docker

install:
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
  - docker run -d -p 127.0.0.1:8042:8042 --name $CONTAINER $REPO

before_script:
  - pip install requests

script:
  - docker ps | grep -q $CONTAINER
  - python tests.py

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker push $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO:$TAG

